//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zebra_RFID_Scanner.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zebra_RFID_Scanner.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã Kiểm Tra.
        /// </summary>
        public static string _checked {
            get {
                return ResourceManager.GetString("checked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sai!.
        /// </summary>
        public static string _false {
            get {
                return ResourceManager.GetString("false", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa Kiểm Tra.
        /// </summary>
        public static string _unchecked {
            get {
                return ResourceManager.GetString("unchecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo Tài Khoản Không Thành Công.
        /// </summary>
        public static string accountcreationfailed {
            get {
                return ResourceManager.GetString("accountcreationfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa Tài Khoản Thành Công.
        /// </summary>
        public static string accountdeletedsuccessfully {
            get {
                return ResourceManager.GetString("accountdeletedsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông Tin Tài Khoản.
        /// </summary>
        public static string accountinformation {
            get {
                return ResourceManager.GetString("accountinformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản Lý Tài Khoản.
        /// </summary>
        public static string accountmanagement {
            get {
                return ResourceManager.GetString("accountmanagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên Tài Khoản.
        /// </summary>
        public static string accountname {
            get {
                return ResourceManager.GetString("accountname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên Tài Khoản Phải Dài Hơn 5 Kí Tự.
        /// </summary>
        public static string accountnamemustbelongerthan6characters {
            get {
                return ResourceManager.GetString("accountnamemustbelongerthan6characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài Khoản.
        /// </summary>
        public static string accounts {
            get {
                return ResourceManager.GetString("accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cài Đặt Tài Khoản Và Cài Đặt Khác.
        /// </summary>
        public static string accountsettingsandmore {
            get {
                return ResourceManager.GetString("accountsettingsandmore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo Tài Khoản Thành Công.
        /// </summary>
        public static string accountsuccessfullycreated {
            get {
                return ResourceManager.GetString("accountsuccessfullycreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoạt Động.
        /// </summary>
        public static string action {
            get {
                return ResourceManager.GetString("action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lịch Sử Hoạt Động.
        /// </summary>
        public static string activityhistory {
            get {
                return ResourceManager.GetString("activityhistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm.
        /// </summary>
        public static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm Màu Sắc.
        /// </summary>
        public static string addcolor {
            get {
                return ResourceManager.GetString("addcolor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm FX Không Thành Công.
        /// </summary>
        public static string addfxfailed {
            get {
                return ResourceManager.GetString("addfxfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm Kích Thước Thất Bại.
        /// </summary>
        public static string addsizefail {
            get {
                return ResourceManager.GetString("addsizefail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm Kích Thước Thành Công.
        /// </summary>
        public static string addsizesuccessfully {
            get {
                return ResourceManager.GetString("addsizesuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã Có Mã.
        /// </summary>
        public static string alreadyhavecode {
            get {
                return ResourceManager.GetString("alreadyhavecode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã Có EPC.
        /// </summary>
        public static string alreadyhaveEPC {
            get {
                return ResourceManager.GetString("alreadyhaveEPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số Lượng Chưa Nhập.
        /// </summary>
        public static string amountnotentered {
            get {
                return ResourceManager.GetString("amountnotentered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật Khẩu Mới.
        /// </summary>
        public static string anewpassword {
            get {
                return ResourceManager.GetString("anewpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tại Dòng.
        /// </summary>
        public static string atline {
            get {
                return ResourceManager.GetString("atline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã Vạch.
        /// </summary>
        public static string barcode {
            get {
                return ResourceManager.GetString("barcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campuchia.
        /// </summary>
        public static string Cambodian {
            get {
                return ResourceManager.GetString("Cambodian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không Thể Mở Tệp Này.
        /// </summary>
        public static string canopenthisfile {
            get {
                return ResourceManager.GetString("canopenthisfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh Mục.
        /// </summary>
        public static string category {
            get {
                return ResourceManager.GetString("category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thay Đổi.
        /// </summary>
        public static string change {
            get {
                return ResourceManager.GetString("change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi Mật Khẩu Thành Công.
        /// </summary>
        public static string changepasswordsuccessfully {
            get {
                return ResourceManager.GetString("changepasswordsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiểm Tra Hàng Hóa.
        /// </summary>
        public static string checkthegoods {
            get {
                return ResourceManager.GetString("checkthegoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn Một Sự Lựa Chọn.
        /// </summary>
        public static string chooseanoption {
            get {
                return ResourceManager.GetString("chooseanoption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn Màu Sắc.
        /// </summary>
        public static string choosecolor {
            get {
                return ResourceManager.GetString("choosecolor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn File.
        /// </summary>
        public static string choosefile {
            get {
                return ResourceManager.GetString("choosefile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn FX.
        /// </summary>
        public static string choosefx {
            get {
                return ResourceManager.GetString("choosefx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn Kích Thước.
        /// </summary>
        public static string choosesize {
            get {
                return ResourceManager.GetString("choosesize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn Phong Cách.
        /// </summary>
        public static string choosestyle {
            get {
                return ResourceManager.GetString("choosestyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa thẻ.
        /// </summary>
        public static string clear {
            get {
                return ResourceManager.GetString("clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa Phong Cách Thành Công.
        /// </summary>
        public static string clearthestyleofsuccess {
            get {
                return ResourceManager.GetString("clearthestyleofsuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đóng.
        /// </summary>
        public static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trùng.
        /// </summary>
        public static string coincide {
            get {
                return ResourceManager.GetString("coincide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Màu Sắc.
        /// </summary>
        public static string color {
            get {
                return ResourceManager.GetString("color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa Màu Không Thành Công.
        /// </summary>
        public static string colorcorrectionfailed {
            get {
                return ResourceManager.GetString("colorcorrectionfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa Màu Thành Công.
        /// </summary>
        public static string colorcorrectionsuccessful {
            get {
                return ResourceManager.GetString("colorcorrectionsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo Màu Không Thành Công.
        /// </summary>
        public static string colorgenerationfailed {
            get {
                return ResourceManager.GetString("colorgenerationfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh Sách Màu.
        /// </summary>
        public static string colorlist {
            get {
                return ResourceManager.GetString("colorlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Màu Không Được Chọn.
        /// </summary>
        public static string colornotselected {
            get {
                return ResourceManager.GetString("colornotselected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa Màu Không Thành Công.
        /// </summary>
        public static string colorremovalfailed {
            get {
                return ResourceManager.GetString("colorremovalfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Màu Sắc Không Được Nhập.
        /// </summary>
        public static string colorsarenotimported {
            get {
                return ResourceManager.GetString("colorsarenotimported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoàn Thành.
        /// </summary>
        public static string complete {
            get {
                return ResourceManager.GetString("complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác Nhận.
        /// </summary>
        public static string confirm {
            get {
                return ResourceManager.GetString("confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo Phong Cách Thành Công.
        /// </summary>
        public static string createasuccessfulstyle {
            get {
                return ResourceManager.GetString("createasuccessfulstyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo Sản Phẩm Lỗi.
        /// </summary>
        public static string createdefectiveproducts {
            get {
                return ResourceManager.GetString("createdefectiveproducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo Sản Phẩm Thành Công.
        /// </summary>
        public static string createsuccessfulproducts {
            get {
                return ResourceManager.GetString("createsuccessfulproducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày.
        /// </summary>
        public static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKU Mặc Định Kiểu Dáng-Màu sắc-Kích thước.
        /// </summary>
        public static string defaultSKUstylecolorsize {
            get {
                return ResourceManager.GetString("defaultSKUstylecolorsize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa Sản Phẩm Bị Lỗi.
        /// </summary>
        public static string deletedefectiveproduct {
            get {
                return ResourceManager.GetString("deletedefectiveproduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa Toàn Bộ Tài Khoản Liên Kết Với FX Này.
        /// </summary>
        public static string deleteentireaccountlinkedwiththisfx {
            get {
                return ResourceManager.GetString("deleteentireaccountlinkedwiththisfx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa FX Thất Bại.
        /// </summary>
        public static string deletefxfailed {
            get {
                return ResourceManager.GetString("deletefxfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa FX Thành Công.
        /// </summary>
        public static string deletefxsuccessfully {
            get {
                return ResourceManager.GetString("deletefxsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa Sản Phẩm Thành Công.
        /// </summary>
        public static string deleteproductsuccessfully {
            get {
                return ResourceManager.GetString("deleteproductsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa Thích Thước Thất Bại.
        /// </summary>
        public static string deletesizefailed {
            get {
                return ResourceManager.GetString("deletesizefailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa Phong Cách Không Thành Công.
        /// </summary>
        public static string deletestylefailed {
            get {
                return ResourceManager.GetString("deletestylefailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô Tả.
        /// </summary>
        public static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi Tiết.
        /// </summary>
        public static string detail {
            get {
                return ResourceManager.GetString("detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi Tiết Hàng Hóa.
        /// </summary>
        public static string detailsofgoods {
            get {
                return ResourceManager.GetString("detailsofgoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài Khoản Có Quyền Quản Lý Không.
        /// </summary>
        public static string doestheaccounthavemanagementrights {
            get {
                return ResourceManager.GetString("doestheaccounthavemanagementrights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không Nhập EPC.
        /// </summary>
        public static string donimportepc {
            get {
                return ResourceManager.GetString("donimportepc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh Sửa.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh Sửa Tài Khoản Thành Công.
        /// </summary>
        public static string editaccountsuccessfully {
            get {
                return ResourceManager.GetString("editaccountsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa Màu.
        /// </summary>
        public static string editcolor {
            get {
                return ResourceManager.GetString("editcolor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh Sửa Kích Thước.
        /// </summary>
        public static string editsize {
            get {
                return ResourceManager.GetString("editsize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh Sửa Kiểu Không Thành Công.
        /// </summary>
        public static string editstylefailed {
            get {
                return ResourceManager.GetString("editstylefailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếng Anh.
        /// </summary>
        public static string english {
            get {
                return ResourceManager.GetString("english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đủ.
        /// </summary>
        public static string enough {
            get {
                return ResourceManager.GetString("enough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mục.
        /// </summary>
        public static string entries {
            get {
                return ResourceManager.GetString("entries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi!.
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mẫu Excel.
        /// </summary>
        public static string exceltemplate {
            get {
                return ResourceManager.GetString("exceltemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xuất.
        /// </summary>
        public static string export {
            get {
                return ResourceManager.GetString("export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo Phong Cách Thất Bại.
        /// </summary>
        public static string failurestyle {
            get {
                return ResourceManager.GetString("failurestyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh Sách Tệp.
        /// </summary>
        public static string filelist {
            get {
                return ResourceManager.GetString("filelist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bộ Lọc.
        /// </summary>
        public static string filter {
            get {
                return ResourceManager.GetString("filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kết thúc và lưu.
        /// </summary>
        public static string finishandsave {
            get {
                return ResourceManager.GetString("finishandsave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa Tài Khoản Lỗi.
        /// </summary>
        public static string fixfaultyaccount {
            get {
                return ResourceManager.GetString("fixfaultyaccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa FX Thành Công.
        /// </summary>
        public static string fixfxsuccessfully {
            get {
                return ResourceManager.GetString("fixfxsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa Lỗi Sản Phẩm.
        /// </summary>
        public static string fixproducterror {
            get {
                return ResourceManager.GetString("fixproducterror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biểu Mẫu Không Đúng Định Dạng.
        /// </summary>
        public static string formisnotinthecorrectformat {
            get {
                return ResourceManager.GetString("formisnotinthecorrectformat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa FX Thất Bại.
        /// </summary>
        public static string fxfixfailed {
            get {
                return ResourceManager.GetString("fxfixfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhận Lỗi EPC.
        /// </summary>
        public static string getEPCerror {
            get {
                return ResourceManager.GetString("getEPCerror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các Mặt Hàng.
        /// </summary>
        public static string goods {
            get {
                return ResourceManager.GetString("goods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh Mục Hàng Hóa.
        /// </summary>
        public static string goodslist {
            get {
                return ResourceManager.GetString("goodslist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa Nhập Mã.
        /// </summary>
        public static string havenotenteredthecode {
            get {
                return ResourceManager.GetString("havenotenteredthecode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa Chọn FX.
        /// </summary>
        public static string haventselectedfx {
            get {
                return ResourceManager.GetString("haventselectedfx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chào.
        /// </summary>
        public static string hi {
            get {
                return ResourceManager.GetString("hi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang Chủ.
        /// </summary>
        public static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã.
        /// </summary>
        public static string id {
            get {
                return ResourceManager.GetString("id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập.
        /// </summary>
        public static string import {
            get {
                return ResourceManager.GetString("import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật Khẩu Không Đúng.
        /// </summary>
        public static string incorrectpassword {
            get {
                return ResourceManager.GetString("incorrectpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập Dữ Liệu EPC.
        /// </summary>
        public static string inputepcdata {
            get {
                return ResourceManager.GetString("inputepcdata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không Đủ.
        /// </summary>
        public static string insufficient {
            get {
                return ResourceManager.GetString("insufficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kết Nối Internet.
        /// </summary>
        public static string internetconnection {
            get {
                return ResourceManager.GetString("internetconnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngắt Kết Nối Internet.
        /// </summary>
        public static string internetdisconnect {
            get {
                return ResourceManager.GetString("internetdisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trong Hệ Thống.
        /// </summary>
        public static string inthesystem {
            get {
                return ResourceManager.GetString("inthesystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to không có trong.
        /// </summary>
        public static string isnotin {
            get {
                return ResourceManager.GetString("isnotin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh Sách Tài Khoản.
        /// </summary>
        public static string listofaccounts {
            get {
                return ResourceManager.GetString("listofaccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng Xuất.
        /// </summary>
        public static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh Mục Chính.
        /// </summary>
        public static string maincategory {
            get {
                return ResourceManager.GetString("maincategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản Lý.
        /// </summary>
        public static string manage {
            get {
                return ResourceManager.GetString("manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mục Lục.
        /// </summary>
        public static string menu {
            get {
                return ResourceManager.GetString("menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm Tài Khoản.
        /// </summary>
        public static string moreaccount {
            get {
                return ResourceManager.GetString("moreaccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm Hàng Hóa.
        /// </summary>
        public static string moregoods {
            get {
                return ResourceManager.GetString("moregoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm Kích Thước.
        /// </summary>
        public static string moresize {
            get {
                return ResourceManager.GetString("moresize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm Phong Cách.
        /// </summary>
        public static string morestylish {
            get {
                return ResourceManager.GetString("morestylish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật Khẩu Mới Phải Lớn Hơn 6 Ký Tự.
        /// </summary>
        public static string newpasswordmustbegreaterthan6characters {
            get {
                return ResourceManager.GetString("newpasswordmustbegreaterthan6characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không Có Mã Nào Được Chọn.
        /// </summary>
        public static string nocodeselected {
            get {
                return ResourceManager.GetString("nocodeselected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không Có Tập Tin Nào Được Chọn.
        /// </summary>
        public static string nofilechosen {
            get {
                return ResourceManager.GetString("nofilechosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa Nhập Tên.
        /// </summary>
        public static string nonamesentered {
            get {
                return ResourceManager.GetString("nonamesentered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa Nhập Mã Sản Phẩm.
        /// </summary>
        public static string noproductcodeentered {
            get {
                return ResourceManager.GetString("noproductcodeentered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa Chọn Mã Sản Phẩm.
        /// </summary>
        public static string noproductcodeselected {
            get {
                return ResourceManager.GetString("noproductcodeselected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa Nhập Số Lượng Quét.
        /// </summary>
        public static string noscannumberentered {
            get {
                return ResourceManager.GetString("noscannumberentered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không Có Phong Cách Nào Được Chọn.
        /// </summary>
        public static string nostyleselected {
            get {
                return ResourceManager.GetString("nostyleselected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Của.
        /// </summary>
        public static string of {
            get {
                return ResourceManager.GetString("of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật Khẩu Cũ.
        /// </summary>
        public static string oldpassword {
            get {
                return ResourceManager.GetString("oldpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tình Trạng Hoạt Động.
        /// </summary>
        public static string operationstatus {
            get {
                return ResourceManager.GetString("operationstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bảng Kê Hàng Hóa.
        /// </summary>
        public static string packinglist {
            get {
                return ResourceManager.GetString("packinglist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật Khẩu.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa Mật Khẩu Không Thành Công.
        /// </summary>
        public static string passwordfixfailed {
            get {
                return ResourceManager.GetString("passwordfixfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật Khẩu Phải Nhiều Hơn 6 Kí Tự.
        /// </summary>
        public static string passwordmustbemorethan6characters {
            get {
                return ResourceManager.GetString("passwordmustbemorethan6characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui Lòng Nhập Tất Cả Dữ Liệu Chính Xác Để Đảm Bảo Hệ Thống.
        /// </summary>
        public static string pleaseenteralldatacorrectlytoensuresystem {
            get {
                return ResourceManager.GetString("pleaseenteralldatacorrectlytoensuresystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui Lòng Kết Nối Lại Với Mạng!.
        /// </summary>
        public static string pleasereconnecttothenetwork {
            get {
                return ResourceManager.GetString("pleasereconnecttothenetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui Lòng Chọn Một Tệp.
        /// </summary>
        public static string pleaseselectafile {
            get {
                return ResourceManager.GetString("pleaseselectafile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhấn Nút.
        /// </summary>
        public static string pressthebutton {
            get {
                return ResourceManager.GetString("pressthebutton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In.
        /// </summary>
        public static string print {
            get {
                return ResourceManager.GetString("print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản Phẩm.
        /// </summary>
        public static string product {
            get {
                return ResourceManager.GetString("product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã Vạch Nhận Dạng Sản Phẩm.
        /// </summary>
        public static string productidentificationbarcode {
            get {
                return ResourceManager.GetString("productidentificationbarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên Sản Phẩm Chưa Được Nhập.
        /// </summary>
        public static string productnamehasnotbeenentered {
            get {
                return ResourceManager.GetString("productnamehasnotbeenentered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số Lượng.
        /// </summary>
        public static string quantity {
            get {
                return ResourceManager.GetString("quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhận EPC Thành Công.
        /// </summary>
        public static string receivedEPCsuccessfully {
            get {
                return ResourceManager.GetString("receivedEPCsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập lại.
        /// </summary>
        public static string reenter {
            get {
                return ResourceManager.GetString("reenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập Lại Mật Khẩu Sai.
        /// </summary>
        public static string reenterincorrectpassword {
            get {
                return ResourceManager.GetString("reenterincorrectpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Làm mới EPC.
        /// </summary>
        public static string refreshepc {
            get {
                return ResourceManager.GetString("refreshepc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tải Lại.
        /// </summary>
        public static string reload {
            get {
                return ResourceManager.GetString("reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa Hàng Hóa.
        /// </summary>
        public static string repairgoods {
            get {
                return ResourceManager.GetString("repairgoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặt Lại Mật Khẩu.
        /// </summary>
        public static string resetpassword {
            get {
                return ResourceManager.GetString("resetpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dư.
        /// </summary>
        public static string residual {
            get {
                return ResourceManager.GetString("residual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thay Đổi Kích Thước Không Thành Công.
        /// </summary>
        public static string resizefailed {
            get {
                return ResourceManager.GetString("resizefailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kêt Quả.
        /// </summary>
        public static string result {
            get {
                return ResourceManager.GetString("result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duyệt Lại.
        /// </summary>
        public static string review {
            get {
                return ResourceManager.GetString("review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu Thay Đổi.
        /// </summary>
        public static string savechanges {
            get {
                return ResourceManager.GetString("savechanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quét Lại.
        /// </summary>
        public static string scanagain {
            get {
                return ResourceManager.GetString("scanagain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm Kiếm Theo Ngày.
        /// </summary>
        public static string seachbyday {
            get {
                return ResourceManager.GetString("seachbyday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm Kiếm.
        /// </summary>
        public static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm Theo Tài Khoản.
        /// </summary>
        public static string searchbyaccount {
            get {
                return ResourceManager.GetString("searchbyaccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn File Để Tải Lên.
        /// </summary>
        public static string selectfilestoupload {
            get {
                return ResourceManager.GetString("selectfilestoupload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn Mã Sản Phẩm.
        /// </summary>
        public static string selectproductcode {
            get {
                return ResourceManager.GetString("selectproductcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số  Xê Ri.
        /// </summary>
        public static string serial {
            get {
                return ResourceManager.GetString("serial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trình Diễn.
        /// </summary>
        public static string show {
            get {
                return ResourceManager.GetString("show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiển Thị 1 Đến.
        /// </summary>
        public static string showingto {
            get {
                return ResourceManager.GetString("showingto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kích Cỡ.
        /// </summary>
        public static string size {
            get {
                return ResourceManager.GetString("size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa Kích Thước Thành Công.
        /// </summary>
        public static string sizecorrectionsuccessful {
            get {
                return ResourceManager.GetString("sizecorrectionsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh Sách Kích Thước.
        /// </summary>
        public static string sizelist {
            get {
                return ResourceManager.GetString("sizelist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kích Thước Không Được Nhập.
        /// </summary>
        public static string sizenotentered {
            get {
                return ResourceManager.GetString("sizenotentered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kích Thước Không Được Chọn.
        /// </summary>
        public static string sizenotselected {
            get {
                return ResourceManager.GetString("sizenotselected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa Kich Thước Thành Công.
        /// </summary>
        public static string sizeremovalsuccessful {
            get {
                return ResourceManager.GetString("sizeremovalsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân Viên.
        /// </summary>
        public static string staff {
            get {
                return ResourceManager.GetString("staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bắt Đầu Quét RFID.
        /// </summary>
        public static string startRFIDscanning {
            get {
                return ResourceManager.GetString("startRFIDscanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng Thái.
        /// </summary>
        public static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng Thái Hiển thị Trạng Thái Hoạt Động Tài Khoản.
        /// </summary>
        public static string statusshowaccountactivitystatus {
            get {
                return ResourceManager.GetString("statusshowaccountactivitystatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dừng Quét RFID.
        /// </summary>
        public static string stopRFIDscanning {
            get {
                return ResourceManager.GetString("stopRFIDscanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STT.
        /// </summary>
        public static string stt {
            get {
                return ResourceManager.GetString("stt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phong Cách.
        /// </summary>
        public static string style {
            get {
                return ResourceManager.GetString("style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh Sửa Phong Cách.
        /// </summary>
        public static string styleediting {
            get {
                return ResourceManager.GetString("styleediting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phong Cách Chưa Được Nhập.
        /// </summary>
        public static string stylehasnotbeenimported {
            get {
                return ResourceManager.GetString("stylehasnotbeenimported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh Sách Phong Cách.
        /// </summary>
        public static string stylelist {
            get {
                return ResourceManager.GetString("stylelist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh Mục Phụ.
        /// </summary>
        public static string subcategory {
            get {
                return ResourceManager.GetString("subcategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành Công!.
        /// </summary>
        public static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo Màu Thành Công.
        /// </summary>
        public static string successfulcolorcreation {
            get {
                return ResourceManager.GetString("successfulcolorcreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa Màu Thành Công.
        /// </summary>
        public static string successfulcolorremoval {
            get {
                return ResourceManager.GetString("successfulcolorremoval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã Thêm FX Thành Công.
        /// </summary>
        public static string successfullyaddfx {
            get {
                return ResourceManager.GetString("successfullyaddfx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa Sản Phẩm Thành Công.
        /// </summary>
        public static string successfulproductrepair {
            get {
                return ResourceManager.GetString("successfulproductrepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh Sửa Phong Cách Thành Công.
        /// </summary>
        public static string successfulstyleediting {
            get {
                return ResourceManager.GetString("successfulstyleediting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vuốt Để Xem Mô Tả.
        /// </summary>
        public static string swipetoseedescription {
            get {
                return ResourceManager.GetString("swipetoseedescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tệp Phải Có Phần Mở Rộng xlsx.
        /// </summary>
        public static string Thefilemusthavetheextensionxlsx {
            get {
                return ResourceManager.GetString("Thefilemusthavetheextensionxlsx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa Nhập Mã Vạch Sản Phẩm.
        /// </summary>
        public static string theproductbarcodehasnotbeenentered {
            get {
                return ResourceManager.GetString("theproductbarcodehasnotbeenentered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Còn Các Mã Hàng Khác.
        /// </summary>
        public static string thereareotheritemcodes {
            get {
                return ResourceManager.GetString("thereareotheritemcodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa Nhập Thời Gian.
        /// </summary>
        public static string timenotentered {
            get {
                return ResourceManager.GetString("timenotentered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa Có.
        /// </summary>
        public static string unavailable {
            get {
                return ResourceManager.GetString("unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không Đạt Yêu Cầu.
        /// </summary>
        public static string unsatisfactory {
            get {
                return ResourceManager.GetString("unsatisfactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập Nhật.
        /// </summary>
        public static string update {
            get {
                return ResourceManager.GetString("update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tải Lên.
        /// </summary>
        public static string upload {
            get {
                return ResourceManager.GetString("upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên Người Dùng Không Được Nhập.
        /// </summary>
        public static string usernamenotentered {
            get {
                return ResourceManager.GetString("usernamenotentered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Việt Nam.
        /// </summary>
        public static string vietnames {
            get {
                return ResourceManager.GetString("vietnames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chúng Tôi Không Thể Chấp Nhận Loại Tệp Này Vào Lúc Này.
        /// </summary>
        public static string wecannotacceptthisfiletypeatthistime {
            get {
                return ResourceManager.GetString("wecannotacceptthisfiletypeatthistime", resourceCulture);
            }
        }
    }
}
