//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zebra_RFID_Scanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailEpc
    {
        public string IdEPC { get; set; }
        public string IdFX { get; set; }
        public string Idstore { get; set; }
        public string IdSerial { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
