//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zebra_RFID_Scanner.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Datum> Data { get; set; }
        public virtual DbSet<DataScanPhysical> DataScanPhysicals { get; set; }
        public virtual DbSet<DetailEpc> DetailEpcs { get; set; }
        public virtual DbSet<Discrepancy> Discrepancies { get; set; }
        public virtual DbSet<File> Files { get; set; }
        public virtual DbSet<FXconnect> FXconnects { get; set; }
        public virtual DbSet<General> Generals { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<XMLValidate> XMLValidates { get; set; }
        public virtual DbSet<EPCDiscrepancy> EPCDiscrepancies { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
    }
}
