//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zebra_RFID_Scanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public string IdFX { get; set; }
        public string User1 { get; set; }
        public string Pass { get; set; }
        public string Name { get; set; }
        public string AddRess { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> Birth { get; set; }
        public Nullable<int> Phone { get; set; }
        public string Description { get; set; }
        public string WorkingHour { get; set; }
        public string GetBitEnd { get; set; }
        public string GetBitGTIN { get; set; }
        public string GetBitItemRef { get; set; }
        public string AddCharacter { get; set; }
        public string TakeAbsoluteValue { get; set; }
        public string CheckDigit { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<bool> Admin { get; set; }
        public Nullable<bool> Status { get; set; }
        public string PrependedCharacter { get; set; }
    
        public virtual FXconnect FXconnect { get; set; }
    }
}
